openapi: 3.0.0
info:
  title: WebGL Experiments API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/zinevich.andr/webglexperiments/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operation available to regular developers
paths:
  /user:
    get:
      tags:
      - developers
      parameters:
      - name: id
        in: query
        description: user id
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
      - bearerAuth: []
components:
  schemas:
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Johnny Depps
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
